name: New Contribution

on:
  workflow_dispatch:
    inputs:
      contribution_name:
        description: "Name for the contribution"
        required: true
        type: string
      contribution_url:
        description: "Link to the contribution"
        required: true
        type: string
      contribution_date:
        description: "When contribution took place"
        required: true
        type: string
      contribution_author:
        description: "Supernova that authored contribution"
        required: true
        type: string
  repository_dispatch:
    types: [manual-update]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update File
        env:
          CONTRIBUTION_NAME: ${{ inputs.contribution_name}}
          CONTRIBUTION_URL: ${{ inputs.contribution_url}}
          CONTRIBUTION_DATE: ${{ inputs.contribution_date}}
          CONTRIBUTION_AUTHOR: ${{ inputs.contribution_author}}
          FILENAME: test.md
          FILE_CONTENTS: "- ($CONTRIBUTION_DATE) ($CONTRIBUTION_NAME)[$CONTRIBUTION_URL] - $CONTRIBUTION_AUTHOR"
        run: |
          echo "$FILE_CONTENTS" > $FILENAME

      - name: Commit Changes
        run: |
          git config --global user.name "Kevin Corbett"
          git config --global user.email "kevin.corbett@postman.com"
          git add $FILENAME
          git commit -m "New Contribution $CONTRIBUTION_NAME by $CONTRIBUTION_AUTHOR"
          git push
