name: New Contribution

on:
  workflow_dispatch:
    inputs:
      contribution_name:
        description: "Name for the contribution"
        required: true
        type: string
      contribution_url:
        description: "Link to the contribution"
        required: true
        type: string
      contribution_date:
        description: "When contribution took place"
        required: true
        type: string
      contribution_author:
        description: "Supernova that authored contribution"
        required: true
        type: string
  repository_dispatch:
    types: [manual-update]

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install @actions/core @actions/github
    - name: Run update-contributions.js
      run: |
        node .github/scripts/update-contributions.js ${{ github.event.inputs.contribution_name }} ${{ github.event.inputs.contribution_date }} ${{ github.event.inputs.contribution_url }} ${{ github.event.inputs.contribution_author }} ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Commit changes
      run: |
        git config --global user.name "Kevin Corbett"
        git config --global user.email "kevin.corbett@postman.com"
        git add .
        git commit -m "Add new contributions"
        git push
